### ISSUE TITLE
Implement the trend following strategy and convert to python

### ISSUE THREAD

**Issue by degencodebeast** [nova-algo/nova-algo#1]
### Description
We need to implement a trend following strategy for our trading bot and convert it to Python. This strategy should identify and follow market trends to make trading decisions. The implementation should be compatible with our existing bot framework and utilize the Drift Protocol.

### Tasks
1. [ ] Review existing trend following strategies and best practices
2. [ ] Create `trendfollowing.py` in `backend/src/strategy/` directory
3. [ ] Define `TrendFollowingStrategy` class, inheriting from `Bot`
4. [ ] Implement required abstract methods from `Bot`:
   - [ ] `init()`
   - [ ] `reset()`
   - [ ] `start_interval_loop()`
   - [ ] `health_check()`
5. [ ] Implement core trend following logic:
   - [ ] Trend identification mechanism (e.g., moving averages, breakouts)
   - [ ] Entry and exit rules
   - [ ] Position sizing
   - [ ] Risk management
6. [ ] Create configuration class in `backend/src/common/types.py`:
   ```python
   @dataclass
   class TrendFollowingConfig(BotConfig):
       # Add relevant configuration parameters here
       pass
   ```
7. [ ] Update `StrategyFactory` class to include new trend following strategy
8. [ ] Write unit tests for `TrendFollowingStrategy` class
9. [ ] Update documentation for new strategy
10. [ ] Optimize strategy for Python and ensure compatibility with Drift Protocol

### Additional Notes
- Ensure the strategy is flexible and can be easily configured
- Consider implementing multiple timeframe analysis for trend confirmation
- Pay attention to performance optimization, especially for real-time trend analysis
- Implement proper error handling and logging

### Related Documentation
- [Drift Protocol Documentation](https://docs.drift.trade/)
- [DriftPy GitHub Repository](https://github.com/drift-labs/driftpy)
- [Drift Jit Maker Bot](https://github.com/drift-labs/keepyrs/tree/master/jit_maker)
- [Drift SDK Docs](https://drift-labs.github.io/v2-teacher/?python#introduction)
