### ISSUE TITLE
Implement the market making strategy 

### ISSUE THREAD

**Issue by degencodebeast** [nova-algo/nova-algo#3]
### Description
We need to implement a market making strategy for our trading bot. This strategy should provide liquidity to the market by continuously placing buy and sell orders. The specific implementation details are left to the discretion of the developer, based on their understanding of market making principles and the provided resources.

### Objectives
- Create a new `MarketMakingStrategy` class that inherits from the `Bot` abstract base class.
- Implement a market making strategy that provides liquidity and manages risk effectively.
- Ensure the strategy is flexible and can be easily configured.

### Tasks
1. [x] Review the provided resources on market making strategies (see Resources on discord, use resources from quant arb and VertoxQuant ).
2. [x] Create a new file `marketmaking.py` in the `backend/src/strategy/` directory.
3. [x] Define the `MarketMakingStrategy` class, inheriting from `Bot`.
4. [x] Implement the required abstract methods from `Bot`:
   - [x] `init()`
   - [x] `reset()`
   - [x] `start_interval_loop()`
   - [x] `health_check()`
5. [x] Design and implement the core market making logic, considering:
   - Order placement strategy
   - Risk management
   - Position sizing
   - Spread management
6. [x] Create a configuration class for the strategy in `backend/src/common/types.py`.
7. [x] Update the `StrategyFactory` class to include the new market making strategy.
8. [x] Write unit tests for the `MarketMakingStrategy` class.
9. [ ] Update documentation to include information about the new strategy.

### Configuration
Create a new configuration class for the market making strategy. The exact parameters will depend on your implementation, but consider including:

````python
@dataclass
class MarketMakingConfig(BotConfig):

# Add relevant configuration parameters here
pass
````
### Additional Notes
- The specific implementation of the market making strategy is left to your discretion. Use your knowledge of market making principles and the information from the provided resources to create an effective strategy.
- Ensure the strategy works well with the existing `DriftAPI` class.
- Consider implementing features that allow for easy adjustment of the strategy's behavior based on market conditions.
- Pay attention to performance optimization, as market making strategies often require quick responses to market changes.

### Related Documentation
- [Drift Protocol Documentation](https://docs.drift.trade/)
- [DriftPy GitHub Repository](https://github.com/drift-labs/driftpy)
- [Drift SDK Docs](https://drift-labs.github.io/v2-teacher/?python#introduction)
- [Drift Jit Maker Bot](https://github.com/drift-labs/keepyrs/tree/master/jit_maker)
